### ISSUE TITLE
创建脚本中的文件上传问题

### ISSUE THREAD

**Issue by JFerdinand** [slyak/smarto#1]
文件上传至.smarto中后，所上传文件都是0kb，请问这是为啥？
![image](https://user-images.githubusercontent.com/23091917/55289152-28e99380-53f5-11e9-80e8-4e3adbdb5ea3.png)

**Comment by JFerdinand** [comment]
![p1](https://user-images.githubusercontent.com/23091917/55527204-97b33f00-56ca-11e9-980e-9fceac84ec69.jpg)
似乎是hash方法影响了输入输出流，把顺序换一下就好了

**Comment by stormning** [comment]
非常棒
